image: r-base

pages:
  stage: deploy
  script:
  - Rscript -e "install.packages('rmarkdown')"
  - make
  - mkdir .public
  - cp -r * .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master