---
Title: "Area Under Normal Curve"
output:
  html_document: default
params: 
  a: -1.2
  b: 0.5
---

```{r setup, include=FALSE}
#knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
dnorm_limit <- function(x) {
 y <- dnorm(x)
 y[x < params$a | x > params$b] <- NA
 return(y)
}
```

## Area Under Standard Normal Curve

Here we find the area under the curve between z=`r params$a` and z=`r params$b`. We find the left tail area up to the right most z-value, then the left tail area up to thte left most z-value.... W

```{r area, echo=FALSE}
#change dev to svg if need to
dat <- data.frame(x=c(-3.5, 3.5))
ggplot(dat, aes(x=x)) +
stat_function(fun=dnorm_limit, geom="area", fill="blue", alpha=0.5) +
stat_function(fun=dnorm) +
labs(x = "z", y = "") +
geom_hline(yintercept=0) +
scale_x_continuous(breaks = seq(-3, 3, by = 1.0)) +
scale_y_continuous(breaks = seq(0, .4, by = 0.2)) +
annotate("text", x = params$b, y = -0.01, label = sprintf("z=%s", params$b)) +
annotate("text", x = params$a, y = -0.01, label = sprintf("z=%s", params$a))
```
