# Rmarkdown problems 

## Confidence Interval Means
Html (web version) : [Html](ConfidenceIntervalMeans.html)  
Pdf (latex version): [Pdf](ConfidenceIntervalMeans.pdf) 
Rmd (source) : [Rmd](ConfidenceIntervalMeans.Rmd) 

## Simple
Html (web version): [Html](Simple.html)  
Pdf (latex version): [Pdf](Simple.pdf) 
Rmd (source) : [Rmd](Simple.Rmd) 

## Test Problem
Html (web version): [Html](Test.html)  
Pdf (latex version): [Pdf](Test.pdf) 
Rmd (source) : [Rmd](Test.Rmd) 

## Standard Normal Shaded Area
Html (web version): [Html](StdNormalShadedArea.html)  
Pdf (latex version): [Pdf](StdNormalShadedAreaTest.pdf) 
Rmd (source) : [Rmd](StdNormalShadedArea.Rmd) 

## Standard Normal Find Area Between
Html (web version): [Html]( StdNormalFindAreaBetween.html)  
Pdf (latex version): [Pdf](StdNormalFindAreaBetween.pdf) 
Rmd (source) : [Rmd](StdNormalShadedAreaTest.Rmd) 

## Image Latex Demo
This one uses Google Chart API to create images for LaTeX.  
This is useful for copy and paste in gmail.  

Html (web version): [Html](ImageLatexDemo.html)  
Pdf (latex version): [Pdf](ImageLatexDemo.pdf) 
Rmd (source) : [Rmd](ImageLatexDemo.Rmd) 

## Normal Curve Find Area Between x-values
Html (web version): [Html](NormalCurveAreaBetween.html)  
Pdf (latex version): [Pdf](NormalCurveAreaBetween.pdf) 
Rmd (source) : [Rmd](NormalCurveAreaBetween.Rmd) 

## Z Table Example
Html (web version): [Html](Table.html)  
Pdf (latex version): [Pdf](Table.pdf) 
Rmd (source) : [Rmd](Table.Rmd) 
