---
title: "Area between"
params:
  a: 22.2
  b: 4 
  mu: 0 
  sigma: 1.0 
jupyter:
  kernelspec:
    display_name: R
    language: R
    name: ir
---

```{r options, eval=FALSE}
options(repr.plot.width=4, repr.plot.height=4)
```

```{r params, include=FALSE}
if(!exists("params")) {
    params<-list(a=1.23,b=1.75,mu=0,sigma=1.0)
}
a<-params$a 
b<-params$b 
mu<-params$mu 
sigma<-params$sigma 
```

```{r setup, include=FALSE}
library(ggplot2)
dnorm_limit <- function(x) {
 y <- dnorm(x)
 y[x < -1.2 | x > 2.1] <- NA
 return(y)
}
```

We are going to find the area between the two x-values by using the standard normal (z) table:

For the left endpoint (x=a) the z-value is:

$$
`r {
    x<-params$a; 
    mu<-params$mu; 
    numer<-(x-mu); 
    sigma<-params$sigma; 
    z<-(x-mu)/sigma
    sprintf("z=\\frac{x-\\mu}{\\sigma}=\\frac{%s-%s}{%s}=\\frac{%s}{%s}=%s",
                                                x,mu,sigma,numer,sigma,z)
   }`
$$

For the right endpoint (x=b) the z-value is:

$$
`r {
    x<-params$b; 
    mu<-params$mu; 
    numer<-(x-mu); 
    sigma<-params$sigma; 
    z<-(x-mu)/sigma
    sprintf("z=\\frac{x-\\mu}{\\sigma}=\\frac{%s-%s}{%s}=\\frac{%s}{%s}=%s",
                                                x,mu,sigma,numer,sigma,z)
   }`
$$

Here is a picture of the area that we want.

```{r area, echo=FALSE}
#change dev to svg if need to
#dat <- data.frame(x=c(-3.5, 3.5))
#ggplot(dat, aes(x=x)) +
#stat_function(fun=dnorm_limit, geom="area", fill="blue", alpha=0.5) +
#stat_function(fun=dnorm) +
#labs(x = "z", y = "") +
#geom_hline(yintercept=0) +
#scale_x_continuous(breaks = seq(-3, 3, by = 1.0)) +
#scale_y_continuous(breaks = seq(0, .4, by = 0.2)) +
#annotate("text", x = -1.2, y = -0.01, label = "hi") +
#annotate("text", x = 2.1, y = -0.01, label = "bye")
```
