# Rmarkdown problems 

## Calculate Z value 
Html (web version):[CalculateZValue.html](CalculateZValue.html)   
Pdf (latex version): [CalculateZValue.pdf](CalculateZValue.pdf)   
Rmd (source) : [CalculateZValue.Rmd](CalculateZValue.Rmd) 

## Confidence Interval Means
Html (web version):[ConfidenceIntervalMeans.html](ConfidenceIntervalMeans.html)   
Pdf (latex version): [ConfidenceIntervalMeans.pdf](ConfidenceIntervalMeans.pdf)   
Rmd (source) : [ConfidenceIntervalMeans.Rmd](ConfidenceIntervalMeans.Rmd) 

## Simple
Html (web version): [Simple.html](Simple.html)  
Pdf (latex version): [Simple.pdf](Simple.pdf)   
Rmd (source) : [Simple.Rmd](Simple.Rmd)    

## Test Problem
Html (web version): [Test.html](Test.html)  
Pdf (latex version): [Test.pdf](Test.pdf)   
Rmd (source) : [Test.Rmd](Test.Rmd) 

## Standard Normal Shaded Area
Html (web version): [StdNormalShadedArea.html](StdNormalShadedArea.html)  
Pdf (latex version): [StdNormalShadedAreaTest.pdf](StdNormalShadedAreaTest.pdf)   
Rmd (source) : [StdNormalShadedArea.Rmd](StdNormalShadedArea.Rmd) 

## Standard Normal Find Area Between
Html (web version): [StdNormalFindAreaBetween.html](StdNormalFindAreaBetween.html)  
Pdf (latex version): [StdNormalFindAreaBetween.pdf](StdNormalFindAreaBetween.pdf)   
Rmd (source) : [StdNormalShadedAreaTest.Rmd](StdNormalShadedAreaTest.Rmd) 

## Image Latex Demo
This one uses Google Chart API to create images for LaTeX.  
This is useful for copy and paste in gmail.  

Html (web version): [ImageLatexDemo.html](ImageLatexDemo.html)     
Pdf (latex version): [ImageLatexDemo.pdf](ImageLatexDemo.pdf)   
Rmd (source) : [ImageLatexDemo.Rmd](ImageLatexDemo.Rmd)   

## Normal Curve Find Area Between x-values
Html (web version): [NormalCurveAreaBetween.html](NormalCurveAreaBetween.html)  
Pdf (latex version): [NormalCurveAreaBetween.pdf](NormalCurveAreaBetween.pdf)   
Rmd (source) : [NormalCurveAreaBetween.Rmd](NormalCurveAreaBetween.Rmd)   

## Z Table Example
Html (web version): [Table.html](Table.html)  
Pdf (latex version): [Table.pdf](Table.pdf)    
Rmd (source) : [Table.Rmd](Table.Rmd) 
